[FSK-22]: Initialize NestJS Repo
fullstacksjs/the-charity-backend pull request #1
Opened 2022-08-31 16:30 UTC by MohammadForoutan

*   configure tsconfig.json
*   add configModule
*   configure environment variables
*   add test for the app module

2022-08-31 16:34 UTC, mhmda-83 approved these changes

2022-08-31 17:43 UTC, ASafaeirad requested changes

2022-08-31 17:43 UTC, ASafaeirad commented on .example.env
> +HOST=
Let's keep a new line at the end of all files, as mentioned in the POSIX standard.

2022-08-31 17:43 UTC, ASafaeirad commented on .gitignore
> +!.vscode/extensions.json
Let's keep a new line at the end of all files, as mentioned in the POSIX standard.

2022-08-31 17:43 UTC, ASafaeirad commented on .npmrc
> +update-notifier=false
Let's keep a new line at the end of all files, as mentioned in the POSIX standard.

2022-08-31 17:43 UTC, ASafaeirad commented on .prettierrc
> +}
Let's keep a new line at the end of all files, as mentioned in the POSIX standard.

2022-08-31 17:43 UTC, ASafaeirad commented on package.json
> +  }
It's a good practice to keep jest config in a separate folder, as It's possible to cache the install step. Changing package.json invalidates that cache.

2022-08-31 17:43 UTC, ASafaeirad commented on src/config/configuration.ts
> +import { IAppConfig } from '../../@types/env';
It's not a good idea to import something outside the `src` boundary.
It's better to keep relevant information as close as possible and move `IAppConfig` into the config folder.

2022-09-01 10:21 UTC, ASafaeirad approved these changes

2022-09-01 10:22 UTC, merged