[FSK-86]: Extract The Configuration Module
fullstacksjs/the-charity-backend pull request #30
Opened 2022-09-27 06:35 UTC by hoseinprd

2022-09-28 12:18 UTC, mhmda-83 requested changes

2022-09-28 12:18 UTC, mhmda-83 commented on src/configuration/EnvironmentVariables.ts
> +  PRISMA_LOG_LEVEL: string;
is there a problem with having 'error' | 'info' | 'query' | 'warn' as type?

2022-09-28 12:18 UTC, mhmda-83 commented on src/configuration/config.ts
> +
I think it's better to remove this space from here.

2022-09-30 07:15 UTC, ASafaeirad commented on src/configuration/EnvironmentVariables.ts
> +  PRISMA_LOG_LEVEL: string;
The type of an environment variable is always a string.

2022-09-30 07:15 UTC, ASafaeirad approved these changes

2022-09-30 07:16 UTC, merged