[FSK-55]: Create Project Implement Resolvers
fullstacksjs/the-charity-backend pull request #31
Opened 2022-10-02 12:29 UTC by MohammadForoutan

- Project entity match with DB schema
- Resolvers implementation
- Do a mutation by API call to create a project
- Created project must be stored in the DB
- Have unit tests
- To have API tests

2022-10-02 14:03 UTC, hoseinprd requested changes

2022-10-02 14:03 UTC, pourdaavar commented on src/project/dto/create-project.dto.ts
> +}
the concept of dto in GraphQL context is different, dto is separated into input and args,
So I suggest separating these ones
```
/dto
----- input/
--------- create-project-input.dto.ts
```
something like that.
after it, if there are multiple types of inputs you can individually export all of them in the index.ts file

2022-10-03 12:49 UTC, pourdaavar requested changes

2022-10-03 12:49 UTC, hoseinprd commented on src/project/project.service.spec.ts
> +      expect(method).toHaveBeenCalled();
`expect(method).toHaveBeenCalled()`

You gonna check if the `create` method is called with correct args or not, but in your test case, you just checked is a method is called or not!

2022-10-04 11:43 UTC, hoseinprd approved these changes

2022-10-05 17:42 UTC, ASafaeirad approved these changes

2022-10-07 10:17 UTC, mhmda-83 approved these changes

2022-10-07 10:19 UTC, merged